### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [goffalex/week6proj1#1]
It looks like this app is actually crashing. Can you fix it please? I'm getting `undefined method `[]' for nil:NilClass` for line 13 of index.erb.

**Comment by goffalex** [comment]
I haven't been able to duplicate this. It works in heroku and when I do rackup from my personal machine. What process/steps are you going through that result in the error? As I understand it the error suggests that line 13 is trying to call a method on a non-existing object, but the object (holidays in this case) is defined on line 11 as far as I can tell. Is my understanding correct?

**Comment by chrisvfritz** [comment]
OK, it does seem to be working now. I'm guessing a temporary outage in the HolidApi during the time I was reviewing your project. I do see another issue though. It looks like this is only showing me the *first* holiday of each month, rather than *all* holidays for the current month and year, and *all* holidays for the month you were born in. You may find [array iteration](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/arrays/iteration.md) useful in fixing that.

**Comment by goffalex** [comment]
I've implemented the iterations and it should be working for all holidays for a given month/year now.

**Comment by chrisvfritz** [comment]
:+1: Much better! Nice work.

## Points of improvement for future projects

### Filename comments

Just so you know for future reference, you don't actually need comments such as `# Gemfile` and `# app.rb` in your files. I just include them in code examples sometimes so you know which file the code would appear in.
